### ISSUE TITLE
Tags to reference this repository in GitHub topics

### ISSUE THREAD

**Issue by marc-bouvier** [juanm4/hexagonal-architecture-frontend#1]
HI,
I have read the readme and glanced at the code of this repo. I believe it is both simple enough and yet it showcases many powerful arguments in favor of hexagonal architecture on the frontend.

Can you add a few tags in the about section of this repository so it can be better referenced for the fellow GitHub users.

Thanks again for the great documentation and sample work you did.

**Comment by juanm4** [comment]
Hi Marc, first of all...thanks for your feedback. When I wrote this article I thought that anybody would read it, but, fortunately, I was wrong. 

As you requested, I have added some tags in the about section to make this article better referenced in the community.

Thanks!
